/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as utils from "./utils/index.js";
export type { utils };
export type { IERC20 } from "./IERC20.js";
