[project]
name = 'sunnyswap'
description = 'SunnySwap - Cross-chain atomic swaps between Stacks and EVM chains'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.stx-htlc]
path = 'contracts/stx-htlc.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
